Fix npe when unsubscribe before google api is connected
skedgo/Android-ReactiveLocation pull request #2
Opened 2017-05-04 05:32 UTC by thuutin

### What is new in this Pull Request ?

This PR only unsubscribe to the leaked listener when the google api client is connected.

2017-05-04 05:56 UTC, thuytrinh commented on android-reactive-location/src/main/java/pl/charmas/android/reactivelocation/observables/location/LocationUpdatesObservable.java
> +            listener.unsubscribe();
I think we should add `@Nullable` to `listener` and always check non-null before calling `unsubscribe()`.

2017-05-04 05:56 UTC, thuytrinh requested changes
Deal w/ nullity of listener

2017-05-05 01:02 UTC, thuutin commented
@thuytrinh Added a null-check

2017-05-05 15:19 UTC, thuytrinh approved these changes

2017-05-05 15:19 UTC, thuytrinh commented
Thanks @thuutin! Let's merge! 👍

2017-05-05 15:20 UTC, merged